plugins {
    kotlin("jvm") version "2.4.20"
    kotlin("plugin.serialization") version "2.4.20"
    id("io.ktor.plugin") version "3.6.0"
}

group = "bayern.kickner"
version = "1.0.0"

repositories {
    mavenCentral()
    maven {
        name = "nexus421MavenReleases"
        url = uri("https://maven.kickner.bayern/releases")
    }
}

dependencies {
    implementation("bayern.kickner:Klogger:0.1.0")
    implementation("bayern.kickner:KotNexLib:4.4.1")

    implementation("io.ktor:ktor-server-core")
    implementation("io.ktor:ktor-server-cio")
    implementation("io.ktor:ktor-server-body-limit")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")

    implementation("jakarta.mail:jakarta.mail-api:2.1.5")
    runtimeOnly("org.eclipse.angus:angus-mail:2.0.5")
    // Ktor logs through SLF4J; without a provider its warnings would be lost and SLF4J complains at startup
    runtimeOnly("org.slf4j:slf4j-simple:2.0.18")

    testImplementation(kotlin("test"))
    testImplementation("io.ktor:ktor-server-test-host")
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
        vendor.set(JvmVendorSpec.AMAZON)
    }
}

application {
    mainClass.set("bayern.kickner.knot.MainKt")
}

ktor {
    fatJar {
        archiveFileName.set("knot.jar")
    }
}

/**
 * Writes `BuildConfig.kt` with the version from this script and the time of the build. The file lives under
 * `build/` and is therefore not versioned. The timestamp is taken when the task runs, so the task is never
 * up to date and the file is rewritten on every build.
 */
abstract class GenerateBuildConfig : DefaultTask() {
    @get:Input
    abstract val version: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        outputs.upToDateWhen { false }
    }

    @TaskAction
    fun generate() {
        val file = outputDir.get().file("bayern/kickner/knot/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package bayern.kickner.knot
            |
            |/** Generated by Gradle on every build (see build.gradle.kts). Do not edit, do not commit. */
            |object BuildConfig {
            |    /** The `version` from build.gradle.kts. */
            |    const val VERSION = "${version.get()}"
            |
            |    /** Time of the build as Unix timestamp in milliseconds. */
            |    const val BUILD_TIME = ${System.currentTimeMillis()}L
            |}
            |""".trimMargin()
        )
    }
}

val generateBuildConfig by tasks.registering(GenerateBuildConfig::class) {
    version.set(project.version.toString())
    outputDir.set(layout.buildDirectory.dir("generated/buildConfig/kotlin"))
}

// Registering the task as source directory makes compileKotlin (and with it test) depend on it
kotlin.sourceSets.main {
    kotlin.srcDir(generateBuildConfig)
}

tasks.test {
    useJUnitPlatform()
}
