package bayern.kickner.knot

import bayern.kickner.knot.notify.timestampFormat
import java.time.Instant
import java.time.ZoneId
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/** BuildConfig is generated by Gradle before compilation. These tests prove the generated values are usable. */
class BuildConfigTest {

    @Test
    fun `version is the one from the build script`() {
        assertTrue(Regex("""\d+\.\d+\.\d+""").matches(BuildConfig.VERSION), "unexpected version '${BuildConfig.VERSION}'")
    }

    @Test
    fun `build time is a plausible unix timestamp in milliseconds`() {
        // 2026-01-01T00:00:00Z as a lower bound, anything below is not a real build time
        assertTrue(BuildConfig.BUILD_TIME > 1_767_225_600_000L, "build time ${BuildConfig.BUILD_TIME} is too old")
        assertTrue(BuildConfig.BUILD_TIME <= System.currentTimeMillis(), "build time ${BuildConfig.BUILD_TIME} lies in the future")
    }
}

class AppVersionTest {

    @Test
    fun `app version names version and formatted build time`() {
        val buildTime = Instant.ofEpochMilli(BuildConfig.BUILD_TIME).atZone(ZoneId.systemDefault()).format(timestampFormat)

        assertEquals("${BuildConfig.VERSION} (built $buildTime)", appVersion)
    }
}
